apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: pipeline
data:
  vector.toml: |
    data_dir = "/var/lib/vector"

    [sources.tlc_jsonl]
    type = "file"
    include = ["/data/*.jsonl"]
    read_from = "beginning"

    [transforms.parse_and_simulate_event_time]
    type = "remap"
    inputs = ["tlc_jsonl"]
    source = '''
    row = parse_json!(.message)
    . = row
    .event_id = uuid_v4()
    .event_time = now()
    '''

    [sinks.redpanda]
    type = "kafka"
    inputs = ["parse_and_simulate_event_time"]
    bootstrap_servers = "redpanda.redpanda.svc.cluster.local:9093"
    topic = "nyc-taxi-events"
    encoding.codec = "json"
    compression = "zstd"

    [sinks.redpanda.buffer]
    type = "disk"
    max_size = 536870912
    when_full = "block"
