apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared-app.yaml
  - vector-app.yaml
  - victoria-scrapes-app.yaml
  - redpanda-topics-app.yaml
  - pipeline-app.yaml
  - metrics-exporter-app.yaml
