statefulset:
  replicas: 1
  podTemplate:
    spec:
      nodeSelector:
        role: data-plane

resources:
  cpu:    { cores: 1 }
  memory:
    container: { max: 1.5Gi }

storage:
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: local-path

tls:
  enabled: false

external:
  enabled: false
