apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redpanda
resources:
  - topic-create-job.yaml
configMapGenerator:
  - name: redpanda-topic-config
    envs:
      - topic.env
generatorOptions:
  disableNameSuffixHash: true
